version: '3'
services:
  rabbitmq:
    image: rabbitmq:management-alpine
    hostname: RabbitNest
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      - RABBITMQ_DEFAULT_USER=rmqadmin
      - RABBITMQ_DEFAULT_PASS=rmqpasswdofadmin
